#!/usr/bin/env python3

import argparse
import writers.crx_manifest as chrome_writer


def version_app():
    arg_parse = argparse.ArgumentParser(prog='PROG')
    arg_parse.add_argument('--version-type', '-v', choices=['major', 'minor', 'patch'], help='Semantic versioning major.minor.patch')
    arg_parse.add_argument('--set-version', help='Set a version with any format.')
    arg_parse.add_argument('--app', '-a', choices=['crx', 'php-composer'], help='type of app file to process')
    arg_parse.add_argument('--file', '-f', help='Input the file path')
    arg_parse.add_argument('--indent', '-i', help='Set indent for JSON files, default is 2')
    arg_parse.add_argument('--increment', '-n', help='Set increment value')

    args = arg_parse.parse_args()

    if args.version_type:
        version_type = args.version_type
    else:
        version_type = args.set_version

    if args.increment == None:
        args.increment = 1

    if args.indent == None:
        args.indent = 2

    if args.app == 'crx':
        chrome_writer.crx_manifest(version_type, args.file, int(args.increment), int(args.indent))

if __name__ == '__main__':
    version_app()
